language: php
php:
  - "5.3"
env:
  global:
    - magento_dir=magento
    - db_host=127.0.0.1
    - db_user=root
    - db_pass=
    - db_name=index-queue-extension
    - db_test_name=${db_name}_test
    - install_sample_data=no
    - base_url=http://index-queue-extension.mage.dev/
    - phpunit_filter=Webgriffe_IndexQueue
  matrix:
    - MAGENTO_VERSION=magento-ce-1.8.1.0
#    - MAGENTO_VERSION=magento-ce-1.7.0.2
#    - MAGENTO_VERSION=magento-ce-1.6.2.0
install:
  - cd ${TRAVIS_BUILD_DIR} && pwd
  - wget https://raw.github.com/netz98/n98-magerun/master/n98-magerun.phar
  - php n98-magerun.phar install --installationFolder=${magento_dir} --dbHost=${db_host} --dbUser=${db_user} --dbPass=${db_pass} --dbName=${db_name} --installSampleData=${install_sample_data} --useDefaultConfigParams=yes --magentoVersionByName=${MAGENTO_VERSION} --baseUrl=${base_url}
  - php n98-magerun.phar cache:clean
  - php n98-magerun.phar cache:disable
  - composer install
  - mysql -uroot -e "CREATE DATABASE \`${db_test_name}\`"
  - cd ${magento_dir}/shell && php ecomdev-phpunit.php --action install && cd ${TRAVIS_BUILD_DIR}
  - cd ${magento_dir}/shell && php ecomdev-phpunit.php --action change-status && cd ${TRAVIS_BUILD_DIR}
  - cd ${magento_dir}/shell && php ecomdev-phpunit.php --action magento-config --db-name ${db_test_name} --base-url ${base_url} && cd ${TRAVIS_BUILD_DIR}
  - wget https://raw.githubusercontent.com/colinmollenhour/modman/master/modman -O modman.sh
  - chmod a+x ${TRAVIS_BUILD_DIR}/modman.sh
  - ${TRAVIS_BUILD_DIR}/modman.sh init magento
  - ${TRAVIS_BUILD_DIR}/modman.sh link ${TRAVIS_BUILD_DIR}

script:
  - cd ${TRAVIS_BUILD_DIR}/${magento_dir} && pwd
  - ${TRAVIS_BUILD_DIR}/vendor/bin/phpunit --version
  - ${TRAVIS_BUILD_DIR}/vendor/bin/phpunit --filter ${phpunit_filter}
